language: node_js

addons:
  postgresql: "9.2"

before_script:
  - cp test/postgres/knexfile.js.dist test/postgres/knexfile.js
  - cp test/sqlite/knexfile.js.dist test/sqlite/knexfile.js
  - psql -U postgres -c 'create database "bookshelf-json-columns";'

node_js:
  - "4"
  - "5"
  - "6"

after_success:
  - npm run coveralls

sudo: false
